services:
  appsmith:
    image: appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - appsmith-stacks
    restart: unless-stopped
    networks: [notanothernet]
    
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sa -d musichall" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    # only for development.
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
  events-service:
    image: msccloudorchestrationeventsservice:latest
    restart: unless-stopped
    env_file:
      - .env.events-service
    ports:
     - 3000:8080

  events-service:
    image: msccloudorchestrationeventsservice:latest
    restart: unless-stopped
    env_file:
      - .env.events-service
    ports:
     - 3000:8080

volumes:
  postgres_data:
  appsmith-stacks:
networks:
  notanothernet:
    driver: bridge
