services:
  
  appsmith:
    image: appsmith/appsmith-ce
    container_name: appsmith
    volumes: 
      - appsmith_stacks:/appsmith-stacks
    restart: unless-stopped
    networks: 
      - notanothernet
    ports: 
      - 80:80
      - 443:443
    
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sa -d musichall" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    # only for development.
    networks: 
      - notanothernet
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - notanothernet
    ports:
      - 8080:8080

  events-service:
    image: msccloudorchestrationeventsservice:latest
    restart: unless-stopped
    env_file:
      - .env.events-service
    networks: 
      - notanothernet
    ports:
      - 3000:8080

  reservations-service:
    image: msccloudorchestrationreservationsservice:latest
    restart: unless-stopped
    env_file:
      - .env.reservations-service
    networks:
      - notanothernet
    ports:
    - 4000:8080

volumes:
  postgres_data:
  appsmith_stacks:
  
networks:
  notanothernet:
    driver: bridge
